<?php 
    $selectorItem = $additionalData['item']; 
    $side = $additionalData['side'];
?>
<?php
    $classes = '';
    if ($selectorItem->isDisabled()) {
        $classes = 'item-disabled';
    }
?>
<li class="item <?php echo $classes; ?>" data-hash="<?php echo $selectorItem->getHash(); ?>">
    <div class="item-icon">
        <?php if ($selectorItem->getIcon() !== ''): ?>
            <span class="<?php echo $selectorItem->getIcon(); ?>"></span>
        <?php endif; ?>
    </div>
    <div class="item-content">
        <div class="item-name" title="<?php echo $selectorItem->getKey(); ?>">
            <?php echo $selectorItem->getName(); ?>
        </div>
        
        <div class="item-data">
            <div class="item-data-content"><?php echo $selectorItem->getDescription(); ?></div>
        </div>
    </div>
    <div class="item-right-area">
        <div class="item-buttons">
            <div class="item-button item-button-add">
                <span class="glyphicon glyphicon-plus"></span>
            </div>
            <div class="item-button item-button-remove">
                <span class="glyphicon glyphicon-remove"></span>
            </div>
        </div>
    </div>
</li>