<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate('Delete group', '\\Zepi\\Web\\AccessControl'); ?></h1>
            
            <div class="message success">
                <?php echo $this->translate('The group was successfully deleted.', '\\Zepi\\Web\\AccessControl'); ?>
            </div>
            
            <div class="button-list">
                <div class="secondary-buttons align-left">
                    <a href="<?php echo $request->getFullRoute('/administration/groups/'); ?>" class="btn btn-default">Zurück</a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
