<?php
    $title = $additionalData['title'];
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-24">
            <h1><?php echo $title; ?></h1>
            
            <div class="message success">
                <?php echo $this->translate('The user was saved successfully.', '\\Zepi\\Web\\AccessControl'); ?>
            </div>
            
            <div class="button-list">
                <div class="secondary-buttons align-left">
                    <a href="<?php echo $request->getFullRoute('/administration/users/'); ?>" class="btn btn-default">Zurück</a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
