<?php 
    $user = $additionalData['user'];
    $password = $additionalData['password'];
    
    $metaInformationManager = $framework->getInstance('\\Zepi\\Web\\General\\Manager\\MetaInformationManager');
    
    $name = $metaInformationManager->getName();
    $username = $user->getName();
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Mail\\Header'); ?>

<table width="640" cellspacing="0" cellpadding="0" bgcolor="#" class="100p">
    <tr>
        <td bgcolor="#EEEEEE" width="640" valign="top" class="100p">
            <div>
                <table width="640" border="0" cellspacing="0" cellpadding="0" class="100p">
                    <tr>
                        <td valign="top">
                            <table border="0" cellspacing="0" cellpadding="0" width="600" class="100p">
                                <tr>
                                    <td height="10"></td>
                                </tr>
                                <tr>
                                    <td width="20"></td>
                                    <td align="left" style="font-size: 36px; color: #000000;">
                                        <font face="'Open Sans', Arial, sans-serif">
                                            <?php echo $this->translate('New password generated', '\\Pmx\\Autopilot\\AccessControl'); ?>
                                        </font>
                                    </td>
                                    <td width="20"></td>
                                </tr>
                                <tr>
                                    <td height="10"></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>
<table width="640" border="0" cellspacing="0" cellpadding="20" class="100p" bgcolor="#FFFFFF">
    <tr>
        <td align="center" valign="top">
            <table border="0" cellpadding="0" cellspacing="0" class="100padtopbottom" width="600">
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('Hello %name%', '\\Pmx\\Autopilot\\AccessControl', array('name' => $username)); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="15"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('You requested a new password for your account.', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="5"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('We generated a new random password and updated your account.', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="20"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('Please use the following password:', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="10"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="Courier New, serif">
                            <?php echo $password; ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="20"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('Please change the password after your next login.', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="10"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('If you have any questions please contact our support.', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td height="20"></td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $this->translate('Best regards', '\\Pmx\\Autopilot\\AccessControl'); ?>
                        </font>
                    </td>
                </tr>
                <tr>
                    <td align="left" class="condensed" valign="top" style="font-size: 16px; color: #000000;">
                        <font face="'Open Sans', Arial, sans-serif">
                            <?php echo $name; ?>
                        </font>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Mail\\Footer'); ?>
                