<?php
    $layoutRenderer = $additionalData['layoutRenderer']; 
    $container = $additionalData['container'];
?>
<div class="userinterface-tabs">
    <ul class="nav nav-tabs" role="tablist">
        <?php foreach ($container->getParts() as $part): ?>
            <li role="presentation" <?php if ($part->isActive()) { ?>class="active"<?php } ?>><a href="#<?php echo $part->getHtmlId(); ?>" role="tab" data-toggle="tab"><?php echo $part->getName(); ?></a></li>
        <?php endforeach; ?>
    </ul>
    <div class="tab-content">
        <?php foreach ($container->getParts() as $part): ?>
            <?php echo $layoutRenderer->render($part); ?>
        <?php endforeach; ?>
    </div>
</div>
