<?php
    use \Zepi\Web\UserInterface\Form\Error;

    $layoutRenderer = $additionalData['layoutRenderer']; 
    $container = $additionalData['container'];
?>
<?php if ($container->hasErrors()): ?>
    <div class="message error">
        <?php echo $this->translate('There were some errors with the submitted data:', '\\Zepi\\Web\\UserInterface'); ?>
        <ul>
            <?php foreach ($container->getErrors() as $error): ?>
                <?php if ($error->getErrorCode() === Error::UNKNOWN_ERROR): ?>
                    <li><?php echo $this->translate('There was an error with the request. Please repeat the action or contact the administrator.', '\\Zepi\\Web\\UserInterface'); ?></li>
                <?php else: ?>
                    <li><?php echo $error->getErrorMessage(); ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
