<?php
    $layoutRenderer = $additionalData['layoutRenderer']; 
    $container = $additionalData['container'];
?>
<?php if ($container->hasErrors()): ?>
    <div class="message error">
        <?php echo $this->translate('There were some errors with the submitted data:', '\\Zepi\\Web\\UserInterface'); ?>
        <ul>
            <?php foreach ($container->getErrors() as $error): ?>
                <li><?php echo $error->getErrorMessage(); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
