<?php
    $layoutRenderer = $additionalData['layoutRenderer']; 
    $container = $additionalData['container'];
    $form = $container->getParentOfType('\\Zepi\\Web\\UserInterface\\Form\\Form');
    
    $showLabel = false;
    $classes = '';
    $additionalClasses = '';
    if ($container->hasLabel() && $container->displayLabel()) {
        $classes = 'col-sm-8 ';
        if ($container->isMandatory()) {
            $additionalClasses .= 'required';
        }
        
        $showLabel = true;
    } else if ($container->fullWidth()) {
        $classes = 'col-sm-12';
    } else {
        $classes = 'col-sm-8 col-sm-offset-4';
    }
?>

<div class="form-group 
    <?php if ($container->hasErrors()): ?>
        has-error
    <?php elseif($form !== false && $form->isSubmitted() && !$container->hasErrors() && !empty($container->getValue())): ?>
        has-success
    <?php endif; ?>
    ">
    <?php if ($showLabel): ?>
        <label for="<?php echo $container->getHtmlId(); ?>" class="col-sm-4 control-label <?php echo $additionalClasses; ?>"><?php echo $container->getLabel(); ?></label>
    <?php endif; ?>

    <div class="<?php echo $classes . ' ' . $additionalClasses; ?>">
        <?php echo $this->templatesManager->renderTemplate($container->getTemplateName(), array('field' => $container)); ?>
        <p class="help-block"><?php echo $container->getHelpText(); ?></p>
        
        <?php if ($container->hasErrors()): ?>
            <?php foreach ($container->getErrors() as $error): ?>
                <p class="help-block"><?php echo $error->getErrorMessage(); ?></p>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>