<?php $field = $additionalData['field']; ?>
<input  type="number" 
        name="<?php echo $field->getHtmlName(); ?>" 
        id="<?php echo $field->getHtmlId(); ?>" 
        placeholder="<?php echo $field->getPlaceholder(); ?>" 
        class="form-control text-right <?php echo $field->getHtmlClasses(); ?>" 
        value="<?php echo $field->getValue(); ?>"
        <?php if ($field->isMandatory()) { echo 'required="required"'; } ?>
        
        <?php if ($field->getMinValue() !== null): ?>
            min="<?php echo $field->getMinValue(); ?>"
        <?php endif; ?>
        
        <?php if ($field->getMaxValue() !== null): ?>
            max="<?php echo $field->getMaxValue(); ?>"
        <?php endif; ?>
        
        <?php if ($field->getTabIndex() !== null): ?>
            tabindex="<?php echo $field->getTabIndex(); ?>"
        <?php endif; ?>
    />