<?php $field = $additionalData['field']; ?>
<div class="selector">
    <div class="selector-selected-area selector-area" data-side="right">
        <div class="selector-area-box">
            <div class="selector-area-title">
                <h2><?php echo $field->getRightTitle(); ?></h2>
            </div>
            <div class="item-search">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-search"></span>
                    </div>
                    <input type="text" id="<?php echo $field->getHtmlId(); ?>-right-search" class="form-control item-search-field <?php echo $field->getHtmlClasses(); ?>"  />
                </div>
            </div>
            <div class="item-list granted-items">
                <ul>
                    <?php foreach ($field->getRightItems() as $item): ?>
                        <?php $this->printTemplate($field->getItemTemplate(), array('item' => $item, 'side' => 'selected')); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="selector-available-area selector-area" data-side="left">
        <div class="selector-area-box">
            <div class="selector-area-title">
                <h2><?php echo $field->getLeftTitle(); ?></h2>
            </div>
            <div class="item-search">
                <div class="input-group">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-search"></span>
                    </div>
                    <input type="text" id="<?php echo $field->getHtmlId(); ?>-left-search" class="form-control item-search-field <?php echo $field->getHtmlClasses(); ?>"  />
                </div>
            </div>
            <div class="item-list available-items">
                <ul>
                    <?php foreach ($field->getLeftItems() as $item): ?>
                        <?php $this->printTemplate($field->getItemTemplate(), array('item' => $item, 'side' => 'available')); ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <input type="hidden" value="" name="<?php echo $field->getHtmlName(); ?>" id="<?php echo $field->getHtmlId(); ?>" class="serialized-selected-items" />
</div>
