<?php
    $result = $additionalData['result'];
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate('Activation', '\\Pmx\\Autopilot\\AccessControl'); ?></h1>
            
            <?php if ($result['result']): ?>
                <div class="message success">
            <?php else: ?>
                <div class="message error">
            <?php endif; ?>
            
                <?php echo $result['message']; ?>
            </div>
            
            <?php if ($result['result']): ?>
                <div class="button-list">
                    <div class="secondary-buttons align-left">
                        <a href="<?php echo $request->getFullRoute('/login/'); ?>" class="btn btn-default">Login</a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
