<?php
    $title = $additionalData['title'];
    
    $result = $additionalData['result'];
    $message = $additionalData['message'];
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-24">
            <h1><?php echo $this->translate('Generate a new password', '\\Pmx\\Autopilot\\AccessControl'); ?></h1>
            
            <div class="message 
                <?php if ($result): ?>
                    success
                <?php else: ?>
                    error
                <?php endif; ?>
                ">
                <?php echo $message; ?>
            </div>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
