<?php
    // Get the data
    $result = $additionalData['result'];
    $errors = $additionalData['errors'];
    $form = $additionalData['form'];
    $layoutRenderer = $additionalData['layoutRenderer'];
    
    $allowRegistration = $additionalData['allowRegistration'];
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate('Login', '\\Zepi\\Web\\AccessControl'); ?></h1>
            
            <?php if ($allowRegistration): ?>
                <div class="message info">
                    <?php echo $this->translate('You need an account? <a href="%link%">Create a new account here</a>.', '\\Zepi\\Web\\AccessControl', array(
                        'link' => $request->getFullRoute('register')
                    )); ?>
                </div>
            <?php endif; ?>
            
            <?php
                // Render the form
                echo $layoutRenderer->render($form);
            ?>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
