<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-24">
            <h1><?php echo $this->translate('Profile', '\\Zepi\\Web\\AccessControl'); ?></h1>
            
            <?php echo $additionalData['overviewPage']; ?>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
