<?php
    $title = $additionalData['title'];
?>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate('Request new password - Email sended', '\\Pmx\\Autopilot\\AccessControl'); ?></h1>
            
            <div class="message success">
                <?php echo $this->translate('We\'ve sent you an email with the instructions to renew your password.', '\\Zepi\\Web\\AccessControl'); ?>
            </div>
        </div>
    </div>
</div>

<?php $this->printTemplate('\\Zepi\\Web\\ThemeZt\\Templates\\Footer'); ?>
