<?php
    use \Zepi\Web\UserInterface\Table\FilterRow;

    $preparedTable = $additionalData['preparedTable'];
?>

<table width="100%" class="table table-striped userinterface-datatable dt-responsive" id="<?php echo $preparedTable->getId(); ?>">
    <?php if ($preparedTable->hasHead() && $preparedTable->getHead()->hasRows()): ?>
        <thead>
            <?php foreach ($preparedTable->getHead()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <th width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></th>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </thead>
    <?php endif; ?>
    
    <?php if ($preparedTable->hasBody() && $preparedTable->getBody()->hasRows()): ?>
        <tbody>
            <?php foreach ($preparedTable->getBody()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <td width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    <?php else: ?>
        <tbody>
            <tr>
                <td colspan="<?php echo $preparedTable->getNumberOfColumns(); ?>">
                    <div class="message info">
                        <?php echo $this->translate('Nothing found.', '\\Zepi\\Web\\UserInterface'); ?>
                    </div>
                </td>
            </tr>
        </tbody>
    <?php endif; ?>
    
    <?php if (($preparedTable->hasFoot() && $preparedTable->getFoot()->hasRows()) || $preparedTable->getTable()->hasPagination()): ?>
        <tfoot>
            <?php foreach ($preparedTable->getFoot()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <th width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></th>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tfoot>
    <?php endif; ?>
</table>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var options = defaultDataTableOptions;

        options.pageLength = 20;
        options.lengthMenu = [ 20, 50, 100 ];
        options.ajax = "<?php echo $request->getFullRoute('user-interface/load-data/' . $preparedTable->getToken()); ?>";
        options.deferRender = true;

        options.language = {
            sEmptyTable: '<?php echo $this->translate('No data available in table', '\\Zepi\\Web\\UserInterface'); ?>',
            sInfo: '<?php echo $this->translate('Showing _START_ to _END_ of _TOTAL_ entries', '\\Zepi\\Web\\UserInterface'); ?>',
            sInfoEmpty: '<?php echo $this->translate('Showing 0 to 0 of 0 entries', '\\Zepi\\Web\\UserInterface'); ?>',
            sInfoFiltered: '<?php echo $this->translate('(filtered from _MAX_ total entries)', '\\Zepi\\Web\\UserInterface'); ?>',
            sInfoPostFix: '',
            sInfoThousands: '<?php echo $this->translate(',', '\\Zepi\\Web\\UserInterface'); ?>',
            sLengthMenu: '<?php echo $this->translate('Show _MENU_ entries', '\\Zepi\\Web\\UserInterface'); ?>',
            sLoadingRecords: '<?php echo $this->translate('Loading...', '\\Zepi\\Web\\UserInterface'); ?>',
            sProcessing: '<?php echo $this->translate('Processing...', '\\Zepi\\Web\\UserInterface'); ?>',
            sSearch: '<?php echo $this->translate('Search:', '\\Zepi\\Web\\UserInterface'); ?>',
            sZeroRecords: '<?php echo $this->translate('No matching records found', '\\Zepi\\Web\\UserInterface'); ?>',
            oPaginate: {
                sFirst: '<?php echo $this->translate('First', '\\Zepi\\Web\\UserInterface'); ?>',
                sLast: '<?php echo $this->translate('Last', '\\Zepi\\Web\\UserInterface'); ?>',
                sNext: '<?php echo $this->translate('Next', '\\Zepi\\Web\\UserInterface'); ?>',
                sPrevious: '<?php echo $this->translate('Previous', '\\Zepi\\Web\\UserInterface'); ?>'
            },
            oAria: {
                sSortAscending: '<?php echo $this->translate(': activate to sort column ascending', '\\Zepi\\Web\\UserInterface'); ?>',
                sSortDescending: '<?php echo $this->translate(': activate to sort column descending', '\\Zepi\\Web\\UserInterface'); ?>'
            }
        };
        
        <?php if ($preparedTable->hasHead() && $preparedTable->getHead()->hasRows()): ?>
            options.columns = <?php echo json_encode($preparedTable->getHead()->getColumnOptions()); ?>
        <?php endif; ?>
        
        $('#<?php echo $preparedTable->getId(); ?>').DataTable(options);
    });
</script>