<?php
    use \Zepi\Web\UserInterface\Table\FilterRow;

    $preparedTable = $additionalData['preparedTable'];
?>

<table width="100%" class="table table-striped userinterface-datatable dt-responsive" id="<?php echo $preparedTable->getId(); ?>">
    <?php if ($preparedTable->hasHead() && $preparedTable->getHead()->hasRows()): ?>
        <thead>
            <?php foreach ($preparedTable->getHead()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <th width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></th>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </thead>
    <?php endif; ?>
    
    <?php if ($preparedTable->hasBody() && $preparedTable->getBody()->hasRows()): ?>
        <tbody>
            <?php foreach ($preparedTable->getBody()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <td width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    <?php else: ?>
        <tbody>
            <tr>
                <td colspan="<?php echo $preparedTable->getNumberOfColumns(); ?>">
                    <div class="message info">
                        <?php echo $this->translate('Nothing found.', '\\Zepi\\Web\\UserInterface'); ?>
                    </div>
                </td>
            </tr>
        </tbody>
    <?php endif; ?>
    
    <?php if (($preparedTable->hasFoot() && $preparedTable->getFoot()->hasRows()) || $preparedTable->getTable()->hasPagination()): ?>
        <tfoot>
            <?php foreach ($preparedTable->getFoot()->getRows() as $row): ?>
                <tr>
                    <?php foreach ($row->getCells() as $cell): ?>
                        <th width="<?php echo $cell->getColumn()->getHtmlWidth(); ?>" class="<?php echo $cell->getColumn()->getClasses(); ?>"><?php echo $cell->getValue(); ?></th>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tfoot>
    <?php endif; ?>
</table>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var options = defaultDataTableOptions;

        options.aoColumns = [
            <?php if ($preparedTable->hasHead() && $preparedTable->getHead()->hasRows()): ?>
                <?php foreach ($preparedTable->getHead()->getRows() as $row): ?>
                    <?php foreach ($row->getCells() as $cell): ?>
                        {
                            <?php if (!$cell->isSortable()): ?>
                                
                            <?php endif; ?>
                        }
                    <?php endforeach; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        ];

        $('#<?php echo $preparedTable->getId(); ?>').DataTable(options);
    });
</script>